### ISSUE TITLE
Update agent schema for update date structure

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/rac_schemas#45]
## Is your feature request related to a problem? Please describe.
AS 3.0+ changes the date structure for json dates in AS.

## Additional context
`"dates_of_existence": [
        {
            "create_time": "2021-06-16T19:12:16Z",
            "system_mtime": "2021-06-16T19:12:16Z",
            "user_mtime": "2021-06-16T19:12:16Z",
            "lock_version": 0,
            "date_label": "existence",
            "date_type_structured": "single",
            "jsonmodel_type": "structured_date_label",
            "structured_date_single": {
                "date_expression": "1915-2017",
                "create_time": "2021-06-16T19:12:16Z",
                "system_mtime": "2021-06-16T19:12:16Z",
                "user_mtime": "2021-06-16T19:12:16Z",
                "lock_version": 0,
                "date_role": "begin",
                "date_standardized_type": "standard",
                "jsonmodel_type": "structured_date_single"
            }
        },
        {
            "create_time": "2021-06-16T19:12:16Z",
            "system_mtime": "2021-06-16T19:12:16Z",
            "user_mtime": "2021-06-16T19:12:16Z",
            "lock_version": 0,
            "date_label": "existence",
            "date_type_structured": "range",
            "jsonmodel_type": "structured_date_label",
            "structured_date_range": {
                "begin_date_standardized": "1915",
                "end_date_standardized": "2017",
                "create_time": "2021-06-16T19:12:16Z",
                "system_mtime": "2021-06-16T19:12:16Z",
                "user_mtime": "2021-06-16T19:12:16Z",
                "lock_version": 0,
                "begin_date_standardized_type": "standard",
                "end_date_standardized_type": "standard",
                "jsonmodel_type": "structured_date_range"
            }
        }
    ],`

**Comment by helrond** [comment]
Thinking about this more I'm not sure we need to change anything in this library, since this validates the transformed data. We _will_ need to change the resources and mappings in Pisces though.

**Comment by p-galligan** [comment]
I think I agree with this after reviewing the model more throughout the day.

I'll close this issue.
