### ISSUE TITLE
regex pattern for titles does not account for newlines

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/rac_schemas#6]
## Describe the bug
Newline characters in Collection and Object title fields cause a validation error. This is because the regex pattern `^(.*)$` does NOT include newline characters.

## Expected behavior
Newline characters in titles should not (I think) cause data to be invalid. OTOH, why in the world would we need a newline character in a title?

## Additional context
I think there are two ways to deal with this:
1. remove the regex pattern from validation
2. remove newlines from titles in AS

@p-galligan any thoughts?

**Comment by p-galligan** [comment]
The easiest solution would be to remove the regex validation, but I don't really think that's the correct way to go. If we can't see a reason to have those characters in the title in the first place, we should remove them.

Do you have a sense on if there are a lot of instances where this happens?

Also, is it just object titles? Or note titles as well?

**Comment by helrond** [comment]
It was happening a lot, but those instances were all in components associated with a small number of resources. The fix which checks for unpublished ancestors (RockefellerArchiveCenter/pisces#260) may also be a fix for this, since it seemed like those were legacy accession resources. 

I wasn't getting any errors on note titles, just object notes.

My sense is that we'd probably want to know if titles have returns in them, so it's probably okay for this error to be thrown. I'm going to leave it as-is and approach this as a data quality issue.
